// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class AddIdiomaTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void addIdioma() {
    driver.get("http://localhost:3000/");
    driver.manage().window().setSize(new Dimension(950, 578));
    assertThat(driver.findElement(By.cssSelector(".btn-group:nth-child(4) > .btn")).getText(), is("Idiomas"));
    driver.findElement(By.cssSelector(".btn-group:nth-child(4) > .btn")).click();
    driver.findElement(By.cssSelector(".text-end:nth-child(2) > .btn")).click();
    driver.findElement(By.id("language")).click();
    driver.findElement(By.id("language")).sendKeys("NUEVO IDIOMA");
    assertThat(driver.findElement(By.cssSelector(".btn:nth-child(2)")).getText(), is("Volver"));
    driver.findElement(By.id("language")).click();
    assertThat(driver.findElement(By.cssSelector(".form-group > .btn:nth-child(1)")).getText(), is("Enviar"));
    driver.findElement(By.cssSelector(".form-group > .btn:nth-child(1)")).click();
    assertThat(driver.findElement(By.cssSelector("tr:nth-child(8) > td:nth-child(1)")).getText(), is("NUEVO IDIOMA"));
  }
}
