// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class TestAddPeliculaTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void testAddPelicula() {
    driver.get("http://localhost:3000/");
    driver.manage().window().setSize(new Dimension(950, 578));
    assertThat(driver.findElement(By.cssSelector("th:nth-child(1)")).getText(), is("Lista de Peliculas"));
    driver.findElement(By.cssSelector(".text-end:nth-child(2) > .btn")).click();
    driver.findElement(By.id("title")).click();
    driver.findElement(By.id("title")).sendKeys("AAAAAAAAAAAAA");
    driver.findElement(By.id("description")).sendKeys("Pelicula");
    driver.findElement(By.id("releaseYear")).sendKeys("2022");
    driver.findElement(By.id("releaseYear")).click();
    driver.findElement(By.id("rating")).click();
    {
      WebElement dropdown = driver.findElement(By.id("rating"));
      dropdown.findElement(By.xpath("//option[. = 'RESTRICTED']")).click();
    }
    driver.findElement(By.id("languageId")).click();
    {
      WebElement dropdown = driver.findElement(By.id("languageId"));
      dropdown.findElement(By.xpath("//option[. = 'Mandarin']")).click();
    }
    driver.findElement(By.cssSelector(".accordion-button")).click();
    driver.findElement(By.cssSelector(".accordion-button")).click();
    assertThat(driver.findElement(By.cssSelector(".accordion-button")).getText(), is("Actores :"));
    driver.findElement(By.cssSelector(".accordion-button")).click();
    assertThat(driver.findElement(By.cssSelector(".card-body > label:nth-child(1)")).getText(), is("Categorias:"));
    driver.findElement(By.id("categories")).click();
    driver.findElement(By.xpath("(//input[@id=\'categories\'])[2]")).click();
    driver.findElement(By.cssSelector(".form-group:nth-child(12) > .errorMsg")).click();
    driver.findElement(By.id("length")).click();
    driver.findElement(By.id("length")).sendKeys("120");
    driver.findElement(By.id("rentalDuration")).click();
    driver.findElement(By.id("rentalDuration")).sendKeys("5");
    driver.findElement(By.id("rentalRate")).click();
    driver.findElement(By.id("rentalRate")).sendKeys("3");
    driver.findElement(By.id("replacementCost")).click();
    driver.findElement(By.id("replacementCost")).sendKeys("20");
    driver.findElement(By.cssSelector(".form-group:nth-child(16)")).click();
    assertThat(driver.findElement(By.cssSelector(".form-group > .btn:nth-child(1)")).getText(), is("Enviar"));
    driver.findElement(By.cssSelector(".form-group > .btn:nth-child(1)")).click();
    js.executeScript("window.scrollTo(0,0)");
    assertThat(driver.findElement(By.cssSelector("th:nth-child(1)")).getText(), is("Lista de Peliculas"));
    assertThat(driver.findElement(By.cssSelector("tr:nth-child(1) > td:nth-child(1)")).getText(), is("AAAAAAAAAAAAA"));
  }
}
